server:
  port: 8756

eureka:
  client:
    # 启用健康检查应该放到application.yml配置，而不应该是bootstrap.yml，否则可能出现 UNKNOWN 的注册状态
    healthcheck:
      enabled: true

spring:
  datasource:
#    去掉MySQL5.7的驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 添加MySQL8.0的驱动类
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springboot
    password: SpringBoot@123
    url: jdbc:mysql://${dynamic.host}/selldb?characterEncoding=utf-8&useSSL=false
    # 是否使用schema.sql建库和data.sql初始化数据，默认true
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#    解决MySQL8.0下错误:Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
#    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # 禁用，否则对GenericKeyedFTPClientPool报错MXBean already registered with name org.apache.commons.pool2:type=GenericKeyedObjectPool,name=pool
  jmx:
    enabled: false

  rabbitmq:
    host: ${dynamic.host}
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  # common spring boot settings
  cache:
    type: redis
    cache-names: redisCache
  redis:
    database: 1
    host: ${dynamic.host}
    port: 6379
    password: redis123
    timeout: 0
#    sentinel:
#      master: mymaster
#      nodes: ${dynamic.host}:26379,${dynamic.host}:26378,${dynamic.host}:26377

helper:
  plugin-gray-deploy:
    request:
      rule:
        data: 1#20190219
        transfer-mode: override_first
  tool-cmp-api:
    nonidempotent:
      redis-key: helper:tool:cmp:api:nonidempotent

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
