host: 127.0.0.1

server:
  port: 8773

spring:
  rabbitmq:
    host: ${dynamic.host}
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://${dynamic.host}:8761/eureka/,http://${dynamic.host}:8762/eureka/,http://${dynamic.host}:8763/eureka/
