dynamic:
  host: '@dynamic.host@'
  url: http://${dynamic.host}
  sslurl: https://${dynamic.host}

spring:
  application:
    name: '@project.build.finalName@'
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EmonCodingBackEnd/project-helpers.git
          search-paths:
            - service-config-repo
          username: Rushing0711
          password: Mt209@3
          basedir: /home/emon/saas/project-helpers/service-config-server/basedir
  security:
    user:
      password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
