server:
  port: 8771

spring:
  rabbitmq:
    host: ${dynamic.host}
    port: 5672
    username: rabbit
    password: rabbit123
    virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://${dynamic.host}:8761/eureka/