env: none

server:
  port: 8781

spring:
#  rabbitmq:
#    host: ${dynamic.host}
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /

eureka:
  client:
    # 启用健康检查应该放到application.yml配置，而不应该是bootstrap.yml，否则可能出现 UNKNOWN 的注册状态
    healthcheck:
      enabled: true

zuul:
  routes:
    template:
      path: /coupon/template/**
      serviceId: coupon-template-provider
      strip-prefix: false
    myProduct:
      path: /product/**
      serviceId: sell-product-provider
      # 设置为空，不配置敏感头
      sensitiveHeaders:
      # 简单写法
#    sell-product-provider: /product/**

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
